alu_add_test 5
alu_sub_test 5
alu_and_test 5
alu_or_test 5
alu_xor_test 5
alu_not_test 5
alu_sll_test 5
alu_srl_test 5
alu_rll_test 5
alu_rrl_test 5
alu_cmpeq_test 5
alu_cmplt_test 5
alu_cmpgt_test 5
alu_reg_reset_test 5
alu_reg_bitbash_test 5
alu_test 10 
alu_nodelay_test 10
alu_longdelay_test 10
alu_error_test 5
